
## GET http://localhost:3000/api/empleados/:pagina
GET http://localhost:3000/api/empleados/1

### GET http://localhost:3000/api/empleados/byId/:idEmpleado
GET http://localhost:3000/api/empleados/byId/4

### GET http://localhost:3000/api/empleados/byPuesto/:idPuesto/:pagina
GET http://localhost:3000/api/empleados/byPuesto/2/2

### GET http://localhost:3000/api/empleados/byPuestoSinPag/:puesto
GET http://localhost:3000/api/empleados/byPuestoSinPag/2

### POST http://localhost:3000/api/empleados/
POST http://localhost:3000/api/empleados/ HTTP/1.1
content-type: application/json

{
      "pwd":"12345779",
      "email": "Leire.rins@example.com",
      "nombre": "Leire",
      "apellidos": "Rins",
      "puesto": 3,
      "idalmacen": 1,
      "num_empleado": "#00690",
      "activo": 1,
      "fecha_contratacion": "2020-10-10 16:20:00"

}

### UPDATE http://localhost:3000/api/empleados/estado/:idEmpleado
PUT http://localhost:3000/api/empleados/estado/14 HTTP/1.1
content-type: application/json

{
      "activo": 0
    }

###  UPDATE http://localhost:3000/api/empleados/almacen/14
PUT http://localhost:3000/api/empleados/almacen/14 HTTP/1.1
content-type: application/json

{
      "idalmacen": 1
    }