
### GET ###
GET http://localhost:3000/api/incidencias/

###
//GET http://localhost:3000/api/incidencias/:idIncidencia/
GET http://localhost:3000/api/incidencias/8/

###
//GET http://localhost:3000/api/incidencias/usuario/:usuario_asignado/
GET http://localhost:3000/api/incidencias/usuario/5/


###
//GET http://localhost:3000/api/incidencias/noVistas/:usuario_asignado/
GET http://localhost:3000/api/incidencias/noVistas/5/

