
### GET ###
GET http://localhost:3000/api/incidencias/

###
//GET http://localhost:3000/api/incidencias/:idIncidencia/
GET http://localhost:3000/api/incidencias/4/

###
//GET http://localhost:3000/api/incidencias/:usuario_asignado/
GET http://localhost:3000/api/incidencias/:usuario_asignado/


###
GET http://localhost:3000/api/incidencias/:usuario_asignado/0
