### GET ###

### GET http://localhost:3000/api/incidencias/:pagina
GET http://localhost:3000/api/incidencias/1

###
//GET http://localhost:3000/api/incidencias/:idIncidencia/
GET http://localhost:3000/api/incidencias/byId/14
###
//GET http://localhost:3000/api/incidencias/byAlmacen/:idAlmacen/:pagina/
GET http://localhost:3000/api/incidencias/byAlmacen/1/1
###
//http://localhost:3000/api/incidencias/byIdPedido/:idpedido
GET http://localhost:3000/api/incidencias/byIdPedido/1

###
//http://localhost:3000/api/incidencias/byNumPedido/:numPedido
GET http://localhost:3000/api/incidencias/byNumPedido/1234567891


###
//GET http://localhost:3000/api/incidencias/usuario/:usuario_asignado/:pagina
GET http://localhost:3000/api/incidencias/usuario/3/1



###
//GET http://localhost:3000/api/incidencias/noVistas/:usuario_asignado/:pagina
GET http://localhost:3000/api/incidencias/noVistas/5/1

### POST ###

POST http://localhost:3000/api/incidencias/ HTTP/1.1
content-type: application/json

{
    "idincidencia": null,
    "titulo": "Faltan cosas",
    "descripcion": "Al pedido X le faltan cosas",
    "idpedido_asociado": 27,
    "tipo_incidencia": 1
}

### PUT ###
//PUT http://localhost:3000/api/incidencias/:idIncidencia
PUT http://localhost:3000/api/incidencias/22 HTTP/1.1
content-type: application/json

{
    "titulo": "Faltan cosas",
    "descripcion": "Al pedido X le faltan cositas",
    "idpedido_asociado": 5,
    "tipo_incidencia": 1,
    "vista": 1
}

### 
//PUT http://localhost:3000/api/incidencias/vista/:idIncidencia
PUT http://localhost:3000/api/incidencias/vista/11

### 
//PUT http://localhost:3000/api/incidencias/noVista/:idIncidencia
PUT http://localhost:3000/api/incidencias/noVista/11


