### PEDIDOS ###
###############

### GET ###
## Obtiene todos los pedidos de la BBDD Paginado
GET http://localhost:3000/api/pedidos/3
### 
## Obtiene todos los pedidos por estado Paginado
GET http://localhost:3000/api/pedidos/estado/3/1
### 
## Obtiene el pedido por el id pedido
GET http://localhost:3000/api/pedidos/byId/29
###
## Obtiene el pedido por el número de pedido
GET http://localhost:3000/api/pedidos/byNumPedido/1234567890/
###
## Obtiene todos los pedidos por un id de empleado Paginado
GET http://localhost:3000/api/pedidos/byEmpleadoId/2/2
###
## Obtiene los pedidos de un responsable Paginado
GET http://localhost:3000/api/pedidos/byResponsableId/19/1
###
##Obtiene todos los pedidos por empleado y estado Paginado
##/byEmpleadoEstado/:usuario_asignado/:estado/:pagina
GET http://localhost:3000/api/pedidos/byEmpleadoEstado/3/1/1
###
##Obtiene los pedidos de un responsable y estado Paginado
##/byResponsableEstado/:usuario_responsable/:estado/:pagina
GET http://localhost:3000/api/pedidos/byResponsableEstado/3/3/1
###
##Obtiene los pedidos de un almacen origen Paginado
##/byAlmacenOrigen/:almacen_origen/:pagina
GET http://localhost:3000/api/pedidos/byAlmacenOrigen/1/3
###
##Obtiene los pedidos de un almacen destino Paginado
##/byAlmacenDestino/:almacen_destino/:pagina
GET http://localhost:3000/api/pedidos/byAlmacenDestino/2/1
###
##Obtiene los pedidos de un encargado
##de su almacen en estado pendiente de validar y si su almacen es el destino pendiente de recepción
##/byEncargado/:idempleado/:pagina
GET http://localhost:3000/api/pedidos/deEncargadoByAlmacen/1/19/1
###
##Obtiene los pedidos de un encargado pendientes de validar
##de su almacen en estado pendiente de validar 
##/byEncargado/:idempleado/:pagina
GET http://localhost:3000/api/pedidos/deEncargadoValidar/1/3/1

###
##Obtiene los pedidos pendientes de recepcionar en un almacén
##de su almacen en estado pendiente de validar y si su almacen es el destino pendiente de recepción
##/byEncargado/:idempleado/:pagina
GET http://localhost:3000/api/pedidos/deEncargadoRecepcionar/1/1
### POST ###
POST http://localhost:3000/api/pedidos/ HTTP/1.1
content-type: application/json

{
    "numero_pedido": "236669005",
    "fecha_creacion": "2023-05-12 08:45:00",
    "almacen_origen": 1,
    "almacen_destino": 2,
    "fecha_entrega": "2023-12-04 23:00:00",
    "usuario_asignado": 2,
    "usuario_responsable": 3,
    "estado": 3,
    "id_transporte": "XYZ780",
    "detalle_pedido": "250 palés de cereales, de 500 kg cada uno."
}
### UPDATE
PUT  http://localhost:3000/api/pedidos/27 HTTP/1.1
content-type: application/json

{
    "numero_pedido": "5735683",
    "fecha_creacion": "2023-07-12 08:45:00",
    "almacen_origen": 1,
    "almacen_destino": 3,
    "fecha_entrega": "2023-12-04 09:00:00",
    "usuario_asignado": 2,
    "usuario_responsable": 3,
    "estado": 3,
    "id_transporte": "XYZ780",
    "detalle_pedido": "250 palés de cereales, de 500 kg cada uno."
}
### 
PUT http://localhost:3000/api/pedidos/toPendienteValidar/2 
###
PUT http://localhost:3000/api/pedidos/toRectificar/2
###
PUT http://localhost:3000/api/pedidos/toValidado/2
###
PUT http://localhost:3000/api/pedidos/toEnTransito/2
###
PUT http://localhost:3000/api/pedidos/toPendienteRecepcionar/2
###
PUT http://localhost:3000/api/pedidos/toFinalizado/2